on: pull_request
name: PR

jobs:
  #  gitHubActionForNpm:
  #    name: Validating Ubuntu
  #    runs-on: ubuntu-latest

  #    steps:
  #      - name: Checking out default branch
  #        uses: actions/checkout@v2
  #        with:
  #          submodules: true
  #      - uses: actions/setup-node@v2
  #        with:
  #          node-version: '10.x'
  #      - name: Install display server dependencies
  #        run: |
  #          sudo apt-get install xvfb libxtst6 libxss1 libgtk2.0-0 -y
  #      - name: Install core libraries for chromium driver
  #        run: |
  #          sudo apt-get install libnss3 libasound2 libgconf-2-4 libgbm1 -y
  #      - name: Running yarn install, prettier and type checks
  #        run: |
  #          yarn install --force --check-files --cache-folder .ycache
  #          yarn prettier-check
  #          yarn type-check
  #      - name: Run Unit tests
  #        run: yarn test-unit

  e2eTestsWin:
    name: Test Desktop App Windows
    runs-on: windows-latest
    env:
      PD_PLATFORM: node
    steps:
      - name: Checking out default branch
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Checkout TestData
        uses: actions/checkout@v2
        with:
          repository: tagspaces/testdata
          path: tests/testdata
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Running npm install, prettier and type checks
        run: |
          npm install
          npm run prepare-node
          npm run prettier-check
          npm run type-check
      - name: Run Unit tests
        run: npm run test-unit
      - name: Run Electron tests
        run: |
          npm run build-e2e
          npm run test-playwright
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-artifacts
          path: |
            tests/test-pages/
            tests/test-reports/
  e2eTestsWebWin:
    name: Test Web App Windows
    runs-on: windows-latest
    env:
      PD_PLATFORM: web
    steps:
      - name: Checking out default branch
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Checkout TagspacesPro
        uses: actions/checkout@v2
        with:
          ref: develop
          repository: tagspaces/tagspacespro
          token: ${{ secrets.CHECKOUT_TSPRO  }}
          path: extensions/tagspacespro
      - name: Checkout TestData
        uses: actions/checkout@v2
        with:
          repository: tagspaces/testdata
          path: tests/testdata
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Running npm install, prettier and type checks
        run: |
          npm install
          npm run prepare-web-pro
          npm run prettier-check
          npm run type-check
      - name: Run Unit tests
        run: npm run test-unit
      - uses: carlosperate/download-file-action@v2
        id: minio
        name: Download the Minio
        with:
          file-url: 'https://dl.min.io/server/minio/release/windows-amd64/archive/minio.RELEASE.2020-11-19T23-48-16Z'
          file-name: 'minio.exe'
          location: './tests/bin/'
      - name: Run Electron tests
        run: |
          npm run build-e2e-web
          npm run test-playwright-web-headless
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-artifacts-pr
          path: |
            tests/test-reports/
            playwright-report/
  # gitHubActionForNpmMac:
  #  name: Validating MacOS
  #  runs-on: macos-latest
  #  steps:
  #    - name: Checking out default branch
  #      uses: actions/checkout@v2
  #      with:
  #        submodules: true
  #    - uses: actions/setup-node@v2
  #      with:
  #        node-version: '10.x'
  #    - name: Running yarn install, prettier and type checks
  #      run: |
  #        yarn install --check-files --cache-folder .ycache
  #        yarn prettier-check
  #        yarn type-check
  #    - name: Run Unit tests
  #      run: yarn test-unit
  #    - name: Run Electron tests
  #      run: |
  #        yarn install-ext
  #        yarn build-main
  #        yarn build-e2e
  #        yarn test-playwright
