name: manual workflow dispatch trigger
on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Command to execute e2e tests default: npm run test-playwright-web-headless'
        required: true
        default: 'test-playwright-web-headless'

jobs:
  e2eTests:
    runs-on: windows-latest
    steps:
      - name: Checking out default branch
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Checkout TestData
        uses: actions/checkout@v2
        with:
          repository: tagspaces/testdata
          path: tests/testdata
      - name: Checkout TagspacesPro
        uses: actions/checkout@v2
        with:
          repository: tagspaces/tagspacespro
          token: ${{ secrets.CHECKOUT_TSPRO  }}
          path: extensions/tagspacespro
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Running npm install, prettier and type checks
        run: |
          npm install
          npm run prepare-node
          npm run prettier-check
          npm run type-check
      - name: Run Unit tests
        run: npm run test-unit
      - uses: suisei-cn/actions-download-file@v1
        id: minio
        name: Download the Minio.exe
        with:
          url: 'https://dl.min.io/server/minio/release/windows-amd64/minio.exe'
          target: tests/bin/
      - name: Run Electron tests
        run: |
          npm run build-e2e
          npm run ${{ github.event.inputs.command }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-pages
          path: tests/test-pages/
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-artifacts
          path: |
            tests/test-pages/
            tests/test-reports/
