name: Nightly E2E Tests Web Minio macOS
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  e2eTestsWebMac:
    name: Test Web App MacOS
    runs-on: macos-latest
    steps:
      - name: Checking out default branch
        uses: actions/checkout@v2
        with:
          ref: develop
          submodules: true
      - name: Checkout TagspacesPro
        uses: actions/checkout@v2
        with:
          repository: tagspaces/tagspacespro
          token: ${{ secrets.CHECKOUT_TSPRO  }}
          path: extensions/tagspacespro
      - name: Checkout TestData
        uses: actions/checkout@v2
        with:
          repository: tagspaces/testdata
          path: tests/testdata
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Running npm install, prettier and type checks
        run: |
          npm install
          npm run prepare-web-pro
          npm run prettier-check
          npm run type-check
      - name: Run Unit tests
        run: npm run test-unit
      - uses: carlosperate/download-file-action@v2
        id: minio
        name: Download the Minio
        with:
          file-url: 'https://dl.min.io/server/minio/release/darwin-amd64/archive/minio.RELEASE.2020-11-19T23-48-16Z'
          file-name: 'minio'
          location: './tests/bin/'
      - name: Check if Minio exists
        run: |
          ls ./tests/bin/
          test -f ./tests/bin/minio
      - name: Make the Minio executable
        run: chmod +x ./tests/bin/minio
      - name: Run Electron tests
        run: |
          npm run build-e2e-web
          npm run test-playwright-web-headless
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-artifacts
          path: |
            tests/test-reports/
            test-results/
            playwright-report/
