name: Nightly E2E Tests Electron MacOS
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  e2eTestsElectronMac:
    name: Test Desktop App Mac
    runs-on: macos-latest
    steps:
      - name: Checking out default branch
        uses: actions/checkout@v2
        with:
          ref: develop
          submodules: true
      - name: Checkout TestData
        uses: actions/checkout@v2
        with:
          repository: tagspaces/testdata
          path: tests/testdata
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Running npm install, prettier and type checks
        run: |
          npm install
          npm run prettier-check
          npm run type-check
      - name: Run Unit tests
        run: npm run test-unit
      - name: Run Electron tests
        run: |
          npm run build-e2e
          npm run test-playwright
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-artifacts
          path: |
            tests/test-reports/
            test-results/
            playwright-report/
